In [2]:
import numpy as np
import pandas as pd

In [5]:
df =pd.read_csv('nums_of_YouTuber_follower.csv')
df.head()

Unnamed: 0                     YouTuber  Follower Number
0           0                   101rabbits            16345
1           1                  1800PetMeds            13872
2           2                AaronsAnimals           714827
3           3               AfroHerpkeeper            25063
4           4  Animal Aid Unlimited, India           233652

In [7]:
stat =np.zeros(5)
for i in range(len(df)):
    lognum= int(np.log10(df['Follower Number'][i]))+1
    stat[lognum-3] +=1

In [8]:
stat

array([ 9., 25., 31., 19.,  4.])

In [12]:
import json
with open('D:/Research/ytList.json', 'r') as f:
    ytList = json.load(f)
df = pd.read_csv('num_of_videos_YouTubers.csv')
df['Names'].head()

0               Brave Wilderness
1                          Maymo
2                       The Dodo
3    Animal Aid Unlimited, India
4                     AntsCanada
Name: Names, dtype: object

In [13]:
count = 0
active_uploads = []
active_yt = []
for i in range(len(df)):
    if df['Names'][i].strip() in ytList:
        count+=1
        active_uploads.append(df['Uploads'][i])
        active_yt.append(df['Names'][i])

In [17]:
new_df = pd.DataFrame({'YouTubers':active_yt,'Videos':active_uploads})
new_df.to_csv('nums_of_videos_YouTubers.csv')

In [41]:
import math
stat = np.zeros(60)
for videos in new_df['Videos']:
    uploads = int(videos.replace(',',''))
    print(uploads)
    print(math.ceil(uploads/100))
    stat[math.ceil(uploads/100)] += 1

543
6
325
4
5150
52
247
3
431
5
997
10
550
6
300
3
82
1
135
2
655
7
243
3
337
4
927
10
110
2
990
10
79
1
342
4
76
1
1169
12
1180
12
398
4
118
2
2440
25
127
2
180
2
714
8
897
9
234
3
383
4
112
2
567
6
631
7
812
9
279
3
318
4
5099
51
101
2
247
3
1061
11
330
4
383
4
1198
12
420
5
88
1
99
1
285
3
346
4
850
9
315
4
446
5
813
9
126
2
750
8
423
5
341
4
585
6
463
5
281
3
420
5
320
4
550
6
210
3
295
3
332
4
409
5
272
3
547
6
572
6
121
2
273
3
171
2
142
2
190
2
306
4
315
4
100
1
271
3
89
1
1295
13
179
2
142
2
68
1
227
3
304
4
209
3
351
4
101
2


In [42]:
np.sum(stat)

88.0

In [43]:
stat

array([ 0.,  8., 15., 15., 17.,  7.,  7.,  2.,  2.,  4.,  3.,  1.,  3.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [46]:
nums_of_YouTubers = 100*np.arange(60)
nums_of_Videos = stat

In [48]:
nums_of_video_YouTuber = pd.DataFrame({'Number of YouTubers':nums_of_YouTubers,'Number of Videos':nums_of_Videos})
nums_of_video_YouTuber.to_csv('nums_of_video_yt_interval.csv')

# Total number of likes Vs Number of YouTuber

In [60]:
import numpy as np
data = np.load('IG_social_avg_max_total.npy')
data.shape

(88, 7)

In [77]:
total_likes = data[:,5]
min(total_likes)

26.0

In [78]:
stat = np.zeros(15)
for likes in total_likes:
    print(likes)
    print(math.ceil(np.log10(likes))+1)
    stat[math.ceil(np.log10(likes))]+=1

213237.0
7
240960.0
7
2281252.0
8
653002.0
7
4707731.0
8
70693.0
6
6120.0
5
1199249.0
8
153027.0
7
12053198.0
9
5062151.0
8
15737238.0
9
317193.0
7
2922163.0
8
1712437.0
8
464837.0
7
27514148.0
9
100831.0
7
14155.0
6
35021.0
6
29069020.0
9
11992.0
6
29078361.0
9
28683.0
6
172093.0
7
2715232.0
8
766385.0
7
99471.0
6
74937.0
6
18514.0
6
3565.0
5
2104985.0
8
157930.0
7
357902.0
7
9298.0
5
25680.0
6
39437431.0
9
2313424.0
8
430628.0
7
273685.0
7
856653.0
7
30547.0
6
14925.0
6
530369.0
7
97368135.0
9
113418.0
7
4097474.0
8
49171.0
6
87330.0
6
125553.0
7
1660269.0
8
118700.0
7
494092.0
7
11472.0
6
487952.0
7
20426.0
6
32090.0
6
169261.0
7
44991.0
6
959637.0
7
75085.0
6
12987.0
6
26.0
3
221511.0
7
109412.0
7
6884.0
5
120878.0
7
711981.0
7
4002.0
5
3002141.0
8
29194.0
6
165001.0
7
120867.0
7
440159.0
7
12764183.0
9
415714.0
7
225887871.0
10
234241.0
7
1808856.0
8
1616758.0
8
25240554.0
9
1463.0
5
473531.0
7
300510.0
7
541237.0
7
311976.0
7
1652570.0
8
14369.0
6


In [83]:
sum(stat[:10])

88.0

In [86]:
interval = 10**np.arange(10)

In [87]:
df3=pd.DataFrame({'Total number of likes':interval,'Number of YouTubers':stat[:10]})
df3.to_csv('num_of_yt_total_likes.csv')

# Total number of comment Vs number of YouTubers

In [91]:
total_comments = data[:,6]
max(total_comments)

3095802.0

In [93]:
stat = np.zeros(15)
for comments in total_comments:
    print(comments)
    print(math.ceil(np.log10(comments))+1)
    stat[math.ceil(np.log10(comments))]+=1

8333.0
5
16944.0
6
23940.0
6
12453.0
6
77590.0
6
2097.0
5
480.0
4
24780.0
6
1947.0
5
125441.0
7
71706.0
6
210452.0
7
11870.0
6
63417.0
6
38072.0
6
8912.0
5
402299.0
7
2927.0
5
417.0
4
890.0
4
666459.0
7
650.0
4
484246.0
7
904.0
4
3318.0
5
38249.0
6
25211.0
6
4187.0
5
2215.0
5
647.0
4
173.0
4
29401.0
6
7654.0
5
16434.0
6
284.0
4
1270.0
5
389579.0
7
34177.0
6
6752.0
5
9160.0
5
16295.0
6
1257.0
5
411.0
4
8931.0
5
1206791.0
8
4163.0
5
152767.0
7
1430.0
5
2762.0
5
5024.0
5
63513.0
6
3987.0
5
2185.0
5
695.0
4
6764.0
5
1670.0
5
923.0
4
7851.0
5
3847.0
5
12690.0
6
2156.0
5
338.0
4
2.0
2
4845.0
5
2179.0
5
243.0
4
7172.0
5
12215.0
6
204.0
4
71504.0
6
1424.0
5
5094.0
5
5595.0
5
4456.0
5
160807.0
7
7284.0
5
3095802.0
8
8154.0
5
71698.0
6
32438.0
6
255067.0
7
121.0
4
7482.0
5
4618.0
5
22150.0
6
5454.0
5
45005.0
6
125.0
4


In [98]:
print(sum(stat[:8]))
print(stat[:8])

88.0
[ 0.  1.  0. 16. 37. 23.  9.  2.]


In [99]:
interval = 10**np.arange(8)

In [100]:
df4=pd.DataFrame({'Total number of comments':interval,'Number of YouTubers':stat[:8]})
df4.to_csv('num_of_yt_total_comments.csv')